### PR TITLE
feat(*): add typescript definitions

### PR DESCRIPTION
**Pull request by stepancar**
Added typescript definitions

### CODE REVIEW

**Comment by stepancar** [comment]
@JamesEggers1 look at this PR, please)

**Comment by JamesEggers1** [comment]
I'll pull in this PR and add it to the next version of the package as soon as I have time a little later this week.

Thank you for the PR!

**Comment by stepancar** [comment]
@JamesEggers1 , just reminder 😃

**Comment by JamesEggers1** [comment]
Package 2.4.1 has been published.

**Pull request merged**
